config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  get 'pages/accueil', as: "accueil"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :interventions, except: [:destroy]
  resources :plaideurinterventions, only: [:new, :create, :destroy]
  resources :ecoles, except: [:destroy]
  resources :users, except: [:destroy]

  get '/plaideurs', to: 'plaideurs#index'
  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :ecoles, only: :show
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ecole.rb
class Ecole < ApplicationRecord
  has_many :professeurs, dependent: :destroy
  has_many :interventions, dependent: :destroy

  include PgSearch
  pg_search_scope :search_ecoles,
    against: [ :nom, :adresse, :code],
    using: {
      tsearch: { prefix: true }
    }

  def to_label
    # method to display the name in simple form association when creating an intervention
    "#{code} - #{nom}"
  end
end

app/models/intervention.rb
class Intervention < ApplicationRecord
  belongs_to :theme
  belongs_to :ecole
  has_many :plaideur_interventions, dependent: :destroy
  has_many :users, through: :plaideur_interventions

  include PgSearch
  pg_search_scope :search_interventions,
    against: [ :date_contact, :date_intervention, :statut],
    associated_against: {
      ecole: [ :nom, :adresse, :responsable, :email],
      theme: [:nom]
    },
    using: {
      tsearch: { prefix: true }
    }


end

app/models/plaideur_intervention.rb
class PlaideurIntervention < ApplicationRecord
  belongs_to :user
  belongs_to :intervention
  validates :user, uniqueness: { scope: :intervention }

  include PgSearch
  pg_search_scope :search_plaideur,
    against: [ :id],
    associated_against: {
      user: [:nom, :prenom]
    },
    using: {
      tsearch: { prefix: true }
    }



end

app/models/professeur.rb
class Professeur < ApplicationRecord
  belongs_to :ecole
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :interventions
  has_many :users

  def to_label
    # method to display the name in simple form association when creating an intervention
    "#{nom}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :theme, optional: true
  has_many :plaideur_interventions, dependent: :destroy
  has_many :interventions, through: :plaideur_interventions

  def to_label
    # method to display the name in simple form association when creating an intervention
    "#{prenom} #{nom}"
  end

  def nom_complet
    "#{prenom} #{nom}"
  end

  include PgSearch
  pg_search_scope :search_by_prenom_nom,
  against: [ :prenom, :nom ],
  using: {
  tsearch: { prefix: true }
  }

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  respond_to :json
end

app/controllers/api/v1/ecoles_controller.rb
class Api::V1::EcolesController < Api::V1::BaseController
  def show
    @ecole = Ecole.find(params[:id])
    # authorize @ecole
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/ecoles_controller.rb
class EcolesController < ApplicationController

  def index
    @ecoles = Ecole.all
    if params[:query] && params[:query] != ''
      @ecoles = @ecoles.search_ecoles(params[:query])
    end
  end

end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :find_intervention, only: [ :update ]

  def index
    @interventions = Intervention.all
    @open_interventions = Intervention.where(statut: 'En cours').sort_by {|intervention| intervention.date_intervention.to_time}
    @unassigned_interventions = Intervention.where(statut: 'Non-assignée').sort_by {|intervention| intervention.date_intervention.to_time}
    @closed_interventions  = Intervention.where(statut: 'Terminée').sort_by {|intervention| intervention.date_intervention.to_time}
    @cancelled_interventions = Intervention.where(statut: 'Annulée').sort_by {|intervention| intervention.date_intervention.to_time}
    @other_interventions = Intervention.where.not(statut: 'En cours').where.not(statut: 'Non-assignée').where.not(statut: 'Terminée').where.not(statut: 'Annulée').sort_by {|intervention| intervention.date_intervention.to_time}

    @plaideurintervention = PlaideurIntervention.new

    # search
    if params[:query] && params[:query] != ''
      matching_interventions = []
      if @interventions.search_interventions(params[:query]).empty?
        plaideurinterventions = PlaideurIntervention.all
        plaideurinterventions = plaideurinterventions.search_plaideur(params[:query])
        plaideurinterventions.each do |plaideurintervention|
          intervention = Intervention.find(plaideurintervention.intervention_id)
          matching_interventions << intervention
        end
      else
        matching_interventions = @interventions.search_interventions(params[:query])
      end
      @open_interventions = matching_interventions.select{|intervention| intervention.statut != 'Terminée' || intervention.statut.nil?}.sort_by {|intervention| intervention.date_intervention.to_time}
      @closed_interventions = matching_interventions.select{|intervention| intervention.statut == 'Terminée'}.sort_by {|intervention| intervention.date_intervention.to_time}
    end
    # assign
    @users_list = User.all

    # update statut
    @statut_list = ["Non-assignée", "En cours", "Terminée", "Annulée"]
  end

  def new
    @intervention = Intervention.new
    @theme_list = Theme.all
  end

  def create
    @intervention = Intervention.new(intervention_params)
    if @intervention.save
      # if user selects a plaideur, then create an instance of plaideurintervention
      unless plaideur_params.empty?
        plaideur_params[:user_ids].each do |plaideur_id|
          plaideur = User.find(plaideur_id)
          @plaideurintervention = PlaideurIntervention.new(intervention: @intervention,
           user: plaideur)
          @plaideurintervention.save
        end
      end
      redirect_to intervention_path(@intervention)
    else
      render :new
    end
  end

  def update
    @intervention.update_attributes(intervention_params)
    if @intervention.save
      redirect_to interventions_path
    end
  end

  private

  def find_intervention
    @intervention = Intervention.find(params[:id])
  end

  def intervention_params
    params.require(:intervention).permit(:date_contact, :date_intervention,
      :theme_id, :ecole_id, :statut)
  end

  def plaideur_params
    params.require(:intervention).permit(:user_ids => [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/plaideurinterventions_controller.rb
class PlaideurinterventionsController < ApplicationController


  def create
    @plaideurintervention = PlaideurIntervention.new(plaideurintervention_params)
    if @plaideurintervention.save
      intervention = Intervention.find(plaideurintervention_params[:intervention_id])
      if intervention.statut == "Non-assignée"
        intervention.statut = "En cours"
        intervention.save
      end
    end
    redirect_to interventions_path
  end

  def destroy
    @plaideurintervention = PlaideurIntervention.find(params[:id])
    intervention = Intervention.find(@plaideurintervention.intervention_id)
    @plaideurintervention.destroy!
    if intervention.users.empty? && intervention.statut == "En cours"
      intervention.statut = "Non-assignée"
      intervention.save
    end
    redirect_to interventions_path
  end

  private

  def plaideurintervention_params
    params.require(:plaideur_intervention).permit(:user_id, :intervention_id)

  end

end

app/controllers/plaideurs_controller.rb
class PlaideursController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index] # À enlever pour la mise en prod

  def index
    if params[:query].present?
      @plaideurs = User.search_by_prenom_nom(params[:query])
    else
      @plaideurs = User.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

end

app/views/ecoles/index.html.erb
<div class="container">
  <h1>Toutes les écoles</h1>
  <div class="search-form" >
    <%= form_tag ecoles_path, method: :get do %>
      <input type="text" class="form-control" id="input-ecoles-search" placeholder="Chercher une école" name="query">
    <% end %>
  </div>
  <% @ecoles.each do |ecole| %>
    <%= render "shared/ecole_card", ecole: ecole %>
  <% end %>

</div>

app/views/interventions/index.html.erb
<div class="container">
  <h1>Toutes les interventions</h1>
  <div class="search-form-interventions" >
    <%= form_tag interventions_path, method: :get do %>
      <input type="text" class="form-control" id="input-interventions-search" placeholder="Chercher une intervention" name="query">
      <%= submit_tag 'Search', class: 'btn btn-primary' %>
    <% end %>
  </div>
  <%= link_to "Voir toutes les interventions", interventions_path  %>

  <h2>Interventions non-assignées</h2>
  <% @unassigned_interventions.each do |intervention| %>
    <%= render "shared/intervention_card", intervention: intervention %>
  <% end %>

  <h2>Interventions ouvertes</h2>
  <% @open_interventions.each do |intervention| %>
    <%= render "shared/intervention_card", intervention: intervention %>
  <% end %>

  <% unless @other_interventions.empty? %>
    <h2>Interventions </h2>
    <% @other_interventions.each do |intervention| %>
      <%= render "shared/intervention_card", intervention: intervention %>
    <% end %>
  <% end %>

  <h2>Interventions terminées</h2>
  <% @closed_interventions.each do |intervention| %>
    <%= render "shared/intervention_card", intervention: intervention %>
  <% end %>

<% unless @cancelled_interventions.empty? %>
  <h2>Interventions annulées</h2>
  <% @cancelled_interventions.each do |intervention| %>
    <%= render "shared/intervention_card", intervention: intervention %>
  <% end %>
<% end %>


</div>

app/views/interventions/new.html.erb
<div class="container">
  <h1>Ajouter une intervention</h1>

  <div id="add_intervention_form">
    <%= simple_form_for @intervention do |f| %>
    <p class="ecole_title">Coordonnées de l'école</p>
    <div class="card">
      <%= f.association :ecole, include_hidden: false, label: false, input_html: {class: 'select2ecoles', id: 'input_ecole'} %>
      <div id="ecole_info">
        <div id="nom_ecole">
          Nom de l'école : <span id="nom_ecole_value"></span>
        </div>
        <div id="code_ecole">
          Code école : <span id="code_ecole_value"></span>
        </div>
        <div id="type_ecole">
          Type d'école : <span id="type_ecole_value"></span>
        </div>
        <div id="adresse_ecole">
          Adresse : <span id="adresse_ecole_value"></span>
        </div>
        <div id="tel_ecole">
          Téléphone : <span id="tel_ecole_value"></span>
        </div>
        <div id="email_ecole">
          Email : <span id="email_ecole_value"></span>
        </div>
        <div id="responsable_ecole">
          Responsable : <span id="responsable_ecole_value"></span>
        </div>
        <div id="enseignants_ecole">
          Enseignants : <span id="enseignants_ecole_value"></span>
        </div>
      </div>
    </div>
    <p class="intervention_title">Demande d'intervention</p>
    <div class="card">
      <%= f.association :theme, label: 'Thème', collection: @theme_list, input_html: {class: 'select2themes'} %>
      <%= f.association :users, include_hidden: false, input_html: { class: 'select2plaideurs' }, label: 'Plaideurs' %>
      <%= f.input :date_intervention, label: "Date de l'intervention", input_html: {class: "datepicker"} %>
    </div>
    <%= f.submit "Créer", class: "btn btn-primary" %>

    <% end %>
  </div>

</div>

app/views/interventions/show.html.erb
<div class="container">
  Thème : <%= @intervention.theme.nom %> <br>
  École : <%= @intervention.ecole.nom %> <br>
  Date de l'intervention : <%= @intervention.date_intervention %> <br>
  Plaideurs :
  <ul>
    <% @intervention.users.each do |plaideur| %>
      <li><%= plaideur.nom_complet %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Plaidoyer CPU</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <% if user_signed_in? %>
       <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>

<div class="accueil_content">
  <div class="accueil_title">
    <h1>QUE VOULEZ VOUS FAIRE ?</h1>
  </div>
  <div class="main-btn">
  <%= link_to new_user_session_path , class: "text-align" do %>
  <button type="button" class="btn btn-secondary large_btn">RECHERCHER UNE INTERVENTION</button>
  <% end %>
  <%= link_to new_user_session_path , class: "text-align" do %>
  <button type="button" class="btn btn-secondary large_btn">ENREGISTRER UNE DEMANDE D'INTERVENTION</button>
  <% end %>
  </div>
  <ul>
  <%= link_to new_user_session_path , class: "text-align" do %>
  <button type="button" class="btn btn-secondary small_btn">Consulter la liste des plaideurs</button>
  <% end %>
   <%= link_to new_user_session_path , class: "text-align" do %>
  <button type="button" class="btn btn-secondary small_btn">Consulter les statistiques</button>
  <% end %>

  <% if user_signed_in? %>
   <%= link_to new_user_session_path , class: "text-align" do %>
    <button type="button" class="btn btn-secondary small_btn">Gestion du site</button>
    <% end %>
  <% end %>
   <%= link_to new_user_session_path , class: "text-align" do %>
  <button type="button" class="btn btn-secondary small_btn">Emailing</button>
  <% end %>
  </ul>
</div>

<% else %>
<div class="home_content">
  <div class="home_logo">
    <%= link_to image_tag("logo.png"), image_path("logo.png"), class: "avatar-large" %>
  </div>
  <div class="home_title">
    <h1>BIENVENUE SUR VOTRE SITE</h1>
  </div>

  <button type="button" class="btn btn-secondary log_in_btn">
      <%= link_to t(".sign_in", default: "SE CONNECTER"), new_user_session_path, class: "text-align" %>
  </button>
  <div class="sign_up_btn">
    <%= link_to "Créer un compte", new_registration_path(resource_name), class: "navbar-wagon-item navbar-wagon-link" %>
  </div>
</div>
<% end %>

app/views/plaideurinterventions/new.html.erb
assigner l'intervention

app/views/plaideurs/index.html.erb
 <%= form_tag plaideurs_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Rechercher un plaideur"
  %>
<% end %>

 <table>
 <tr>
  <th> PRENOM </th>
  <th> NOM </th>
  <th> TEL </th>
  <th> NIVEAU </th>
 </tr> 
<% @plaideurs.each do |plaideur| %>
 <tr> 
  <td><%= plaideur.prenom %></td>
  <td><%= plaideur.nom %></td>
  <td><%= plaideur.tel %></td>
  <td><%= plaideur.niveau %></td>
 </tr>
 <% end %>
</table>

app/views/shared/_assign_form.html.erb
<%= simple_form_for [intervention, plaideurintervention], :url => intervention_plaideurinterventions_path(intervention), :method => :post do |f| %>
    <% if plaideurintervention.errors.any? %>
      <div class="errors-container">
        <ul>
          <% plaideurintervention.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.association :user, collection: @users_list%>
    <%= f.button :submit,'Assigner', class: 'btn-primary'%>
  <% end %>

app/views/shared/_ecole_card.html.erb
École : <%= ecole.nom %> <br>
Email : <%= ecole.email %> <br>
Téléphone : <%= ecole.telephone %> <br>
Responsable : <%= ecole.responsable %> <br>
<br>
<br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_intervention_card.html.erb
<div class="card intervention-card">
  <div class="intervention-card-essentiels">
    <div class="intervention-section intervention-card-date">
      <strong>Date de l'intervention :</strong> <%= intervention.date_intervention %>
    </div>
    <div class="intervention-section intervention-card-theme">
      <strong>Thème :</strong> <%= intervention.theme.nom %>
    </div>
    <div class="intervention-section intervention-card-statut">
      <% if current_user.admin %>
        <%= simple_form_for intervention do |f| %>
          <%= f.input :statut, collection: @statut_list, include_blank: false, include_hidden: false %>
          <%= f.button :submit,'Mettre à jour', class: 'btn-primary btn-sm'%>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="intervention-section intervention-card-ecole">
    <strong>École :</strong> <%= intervention.ecole.nom %> <br>
    <%= intervention.ecole.adresse %> <br>
    <strong>Responsable :</strong> <%= intervention.ecole.responsable %> (<%= intervention.ecole.email %>) <br>
  </div>
  <div class="intervention-card-assign-container">
    <div class="intervention-section intervention-card-all-plaideurs">
      <% unless intervention.users.empty? %>
        <% intervention.users.each do |plaideur| %>
          <div class="intervention-card-plaideur">
            <strong>Plaideur :</strong> <%= "#{plaideur.prenom} #{plaideur.nom}" %>
            <% plaideurintervention_instance = PlaideurIntervention.where(intervention_id: intervention.id).where(user_id: plaideur.id).first %>
            <% if current_user.admin == true %>
              <%= link_to plaideurintervention_path(plaideurintervention_instance), :method => :delete do %>
                <i class="fas fa-times"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <% if current_user.admin == true %>
      <%= simple_form_for @plaideurintervention, :url => plaideurinterventions_path, :method => :post do |f| %>
        <%= f.association :user, collection: @users_list, class: "intervention-section" %>
        <%= f.input :intervention_id, :as => :hidden, :input_html => { :value => intervention.id } %>
        <%= f.button :submit,'Assigner', class: 'btn-primary'%>
      <% end %>
    <% end %>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Interventions", interventions_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Plaideurs", plaideurs_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Ecoles", ecoles_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Interventions", interventions_path  %></li>
        <li><%= link_to "Ecoles", ecoles_path %></li>
        <li><%#= link_to "Plaideurs", plaideurs_path  %></li>
      </ul>
    </div>
  </div>
</div>